version: '3.8'

services:

  test-postgres-db:
    container_name: test-postgres-db
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - test-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer-test
    image: adminer
    restart: no
    ports:
      - "8088:8080"

volumes:
  test-data:
    name: test-volume